# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a4a428b2f7db5ef9d5b20ce18ca8daa324da977cda4af98eeb8a1d65f73fd6a7088bf67c790b2fa6ce247371bd9636bd4755933a197bd4b450bd1ca9901dba1

test:
  secret_key_base: 1ca3a11abc702ed1f686670e5b334dcf58b43f191f458933ddb13c83d9b26346d38de9c5d16256650386d61b505213fcceba67fc5a1c2ce9a4949e67b5a53d59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
